### ISSUE TITLE
Date Picker: Name is not properly defined for the selected year button

### ISSUE THREAD

**Issue by yeah1900** [microsoft/fluentui#14103]
### Environment Information

- **Package version(s)**: all
- **Browser and OS versions**: all

### Describe the issue:

Screen reader announces the year button as ‘2020’ button which doesn’t clear the purpose of the control.
![image](https://user-images.githubusercontent.com/416066/87919108-e7796d80-caa9-11ea-810a-a58072d2f6fa.png)

### Please provide a reproduction of the issue in a codepen:
Go to Date Picker demo page, you can see the issue.
https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker

#### Actual behavior:
It now reads "2019" button.

#### Expected behavior:

There was a similar issue earlier: https://github.com/microsoft/fluentui/issues/10352 which concluded:
> I think that's a reasonable label, "2019, select to change the year". Lets go with that one, using the string formatting I described above. We won't touch the month button.

**Comment by paulgildea** [comment]
Dupe of #10352.

**Comment by yeah1900** [comment]
Hi @paulgildea , although it's duplicate of https://github.com/microsoft/fluentui/issues/10352, it has not been fixed yet. Could you please advise when someone would take a look and fix it?

**Comment by paulgildea** [comment]
@yeah1900 My mistake. Looking at the dup it stated it was addressed. I'll add this back to our investigation queue.

**Comment by paulgildea** [comment]
@lorejoh12 FYI

**Comment by xugao** [comment]
@lorejoh12 - could you take a look at this? I think we should allow user to customize the aria-label but still having this as default:
```
 aria-label={String(year)}
```

**Comment by KeiraYang** [comment]
Hi @lorejoh12. Is there update on this bug? We're facing the same issue on it. Thanks!
