### ISSUE TITLE
Duplicate export names from @fluentui/react due to export stars

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#20178]
The `@fluentui/react` package index file and subsequent graph has the following cross-package namespace exports:

```jsx
export * from "@fluentui/utilities";
export * from "@fluentui/style-utilities";
export * from "@fluentui/react-window-provider";
export * from "@fluentui/react-focus";
export * from "@fluentui/font-icons-mdl2";
export * from "@fluentui/theme";
```

I created a bundle for each of these packages and then try to load them in the browser using an import map. Requesting `createTheme` from `@fluentui/react` results in this error:

> The requested module '@fluentui/react' contains conflicting star exports for name 'createTheme'

It turns out that because of the above star exports, the primary suite package is actually exporting duplicated names:

1. `@fluentui/theme` defines and exports `createTheme`
2. `@fluentui/style-utilities` exports `createTheme` from `@fluentui/theme`
3. `@fluentui/react` exports star from both

Star exports are the real issue; they effectively give permission for a library's API surface to shift depending on sub dependency versions, effectively making it impossible to enforce semver on the contract. More serious than that, they allow sub dependencies to introduce name conflicts without technically violating semver.

Recommendation:

Replace the cross-package export stars with named exports, exporting a set of names that originate from the source rather than from indirection. (E.g. if `@fluentui/theme` defines `createTheme`, then `@fluentui/react` should export it from that library, rather than from `@fluentui/style-utilities` redirection. Explicitly named exports will help ensure that API surface contracts don't shift accidentally, and will help ensure semver is bumped properly when new names are exported.

This could be done as a 1 time fix manually, or better using some automated tooling. ts-morph would be one idea: load up the project, find all export stars, traverse the exports they represent, remove the export * line and replace with named exports.

Ideally however an eslint rule could be defined to throw when cross-package export stars are used, and auto-fixing expands to the list of names coming from the package. This would get the author a chance to review/fix name collisions and omit unnecessary exports, and enforce the bad pattern is avoided across all repos.

**Comment by dzearing** [comment]
This can be linted from the repo (but not autofixed) using

```json
    "no-restricted-syntax": [
      "error",
      {
        "selector": "ExportAllDeclaration[source.value=/^[^.]{1}.+$/]",
        "message": "No exporting star from external packages, {insert explanation}"
      }
    ]
```

**Comment by gouttierre** [comment]
@dzearing - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows. 

@khmakoto  - Would you be able to assist with the duplicate names being exported and confirm if this is a regression issue?

**Comment by dzearing** [comment]
Just to add more context; Tommy on Jason's team is working on a lint rule (https://github.com/microsoft/rnx-kit/pull/810#pullrequestreview-799095352) to catch this and auto expand cross-library export *s. It's almost working, and I can submit a PR once it's done to integrate it into the fui repo so I'll just need @khmakoto to review. No work needed just yet. There may be minor work to enable the rule across packages once the initial change is made though, but i think it may be easy enough to do in a bulk run.

**Comment by khmakoto** [comment]
@dzearing more than happy to review once that PR is up, let me know once it's ready.

**Comment by callmedhh** [comment]
Is there any update on this issue? We are blocked by this during upgrading to webpack v5.

**Comment by dzearing** [comment]
I believe this has been resolved; There are no more export *s in FUI libraries.

**Comment by TeckTn** [comment]
> I believe this has been resolved since 8.44; There are no more export *s in FUI libraries.

Hi, I have 8.50 and I am still seeing this issue : 

Compiled with problems:X

```
ERROR in ./.yarn/__virtual__/@fluentui-react-virtual-bd01deabbc/0/cache/@fluentui-react-npm-8.52.1-f97c2b2272-d1e4bf974b.zip/node_modules/@fluentui/react/lib/index.js 84:0-24

The requested module './Theme' contains conflicting star exports for the names 'AnimationStyles', 'AnimationVariables', 'DefaultEffects', 'DefaultFontStyles', 'DefaultPalette', 'createFontStyles' with the previous requested module './Styling'
```
Is there any chance that this will be fixed so I can upgrade to v5 ?

**Comment by rogerprz** [comment]
Still seeing this issue. Just started occurring. On latest version ` "@fluentui/react": "^8.52.2",`

```
The requested module './Theme' contains conflicting star exports for the names 'AnimationStyles', 'AnimationVariables', 'DefaultEffects', 'DefaultFontStyles', 'DefaultPalette', 'createFontStyles' with the previous requested module './Styling'
```

**Comment by bonafideyan** [comment]
Still seeing this issue. Just started occurring. On latest version "@fluentui/react": "^8.52.3",

**Comment by khmakoto** [comment]
@TeckTn @rogerprz @bonafideyan #21608 was merged one hour ago and should fix this issue in the version coming tomorrow, could you please check if it is fixed then?
