### ISSUE TITLE
[Bug]: Using FluentUI/react in server rendered environment with Nextjs throws useLayoutEffect warning in Pivot component

### ISSUE THREAD

**Issue by sanchit121** [microsoft/fluentui#23816]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 9.10 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 13.1.2
```

### Reproduction

https://codesandbox.io/s/nextjs-client-server-content-mismatch-forked-xyfxjq

## Actual Behavior
Pivot element gives warning as 
Warning: useLayoutEffect does nothing on the server, because its effect
in SSR environment with Next JS.
There is already a PR related to this, but not sure if that is fixing issue in Pivot. I have commented on PR yesterday and the developer (@ecraig12345 ) asked me to create a issue for this.
Link of PR: https://github.com/microsoft/fluentui/pull/21899

## Expected Behavior
Pivot element should not give warning.

Note: I tried to provide a fix but unable to find reference for useLayoutEffect, May be someone can help here ? I am willing to contribute.

### Logs

```shell
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
    in Pivot
    in StyledPivot (at pages/index.js:8)
    in div (at pages/index.js:6)
    in IndexPage
    in App
    in Unknown
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in AppContainer
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
    in Pivot
    in StyledPivot (at pages/index.js:8)
    in div (at pages/index.js:6)
    in IndexPage
    in App
    in Unknown
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in AppContainer
```

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Related issue #22515

**Comment by sopranopillow** [comment]
Hi @sanchit121, issue #22515 should fix this problem.

**Comment by sanchit121** [comment]
@sopranopillow Thats exactly the issue is, Even after this PR is merged, I am seeing the warning,

I have given the working code sandbox example with latest version

This is not fixed.

**Comment by sanchit121** [comment]
cc @ecraig12345

**Comment by sopranopillow** [comment]
> @sopranopillow Thats exactly the issue is, Even after this PR is merged, I am seeing the warning,
> 
> I have given the working code sandbox example (https://codesandbox.io/s/nextjs-client-server-content-mismatch-forked-xyfxjq) with latest version
> 
> This is not fixed.

sorry, that was the wrong issue, here's the PR that actually fixes it: #23847. Also, ecraig12345 has shifted to another team (occasionally still contributes), but please refer to one of the most recent contributors for help 🙂

**Comment by sanchit121** [comment]
Ok Thank you for resolving this.
